# Generated by Django 6.0.3 on 2026-03-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assistant', models.CharField(choices=[('assistant1', 'Assistant 1'), ('assistant2', 'Assistant 2'), ('assistant3', 'Assistant 3')], max_length=50)),
                ('meeting_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='city_thumbnails/')),
                ('flyin_graphic', models.ImageField(upload_to='city_flyin_graphics/')),
                ('loop_graphic', models.ImageField(upload_to='city_loop_graphics/')),
                ('support_audio', models.FileField(upload_to='city_support_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
