# Generated by Django 6.0.3 on 2026-03-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_active_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='flyin_graphic',
            field=models.ImageField(blank=True, null=True, upload_to='city_flyin_graphics/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='loop_graphic',
            field=models.ImageField(blank=True, null=True, upload_to='city_loop_graphics/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='support_audio',
            field=models.FileField(blank=True, null=True, upload_to='city_support_audios/'),
        ),
    ]
