# Generated by Django 6.0.3 on 2026-03-30 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_city_flyin_graphic_alter_city_loop_graphic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('assistant', models.CharField(choices=[('assistant1', 'Assistant 1'), ('assistant2', 'Assistant 2'), ('assistant3', 'Assistant 3')], max_length=50)),
                ('meeting_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='room_thumbnails/')),
                ('flyin_graphic', models.ImageField(blank=True, null=True, upload_to='room_flyin_graphics/')),
                ('loop_graphic', models.ImageField(blank=True, null=True, upload_to='room_loop_graphics/')),
                ('support_audio', models.FileField(blank=True, null=True, upload_to='room_support_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
        ),
    ]
