# Generated by Django on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_avatar_url_user_contact_no_user_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatars/', null=True, blank=True),
        ),
    ]
