# Generated by Django 6.0.4 on 2026-04-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_date_joined_user_role_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
