# Generated by Django 6.0.4 on 2026-04-14 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_activitylog_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cities', to=settings.AUTH_USER_MODEL),
        ),
    ]
