# Generated by Django 6.0.4 on 2026-04-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_thumbnailasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
