# Generated by Django 6.0.4 on 2026-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='flyin_graphic',
        ),
        migrations.RemoveField(
            model_name='city',
            name='loop_graphic',
        ),
        migrations.RemoveField(
            model_name='city',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='room',
            name='flyin_graphic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='loop_graphic',
        ),
        migrations.RemoveField(
            model_name='room',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='thumbnailasset',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='city',
            name='flyin_graphic_avif',
            field=models.ImageField(blank=True, null=True, upload_to='city_flyin_graphics/avif/'),
        ),
        migrations.AddField(
            model_name='city',
            name='flyin_graphic_original',
            field=models.ImageField(blank=True, null=True, upload_to='city_flyin_graphics/'),
        ),
        migrations.AddField(
            model_name='city',
            name='flyin_graphic_webp',
            field=models.ImageField(blank=True, null=True, upload_to='city_flyin_graphics/webp/'),
        ),
        migrations.AddField(
            model_name='city',
            name='loop_graphic_avif',
            field=models.ImageField(blank=True, null=True, upload_to='city_loop_graphics/avif/'),
        ),
        migrations.AddField(
            model_name='city',
            name='loop_graphic_original',
            field=models.ImageField(blank=True, null=True, upload_to='city_loop_graphics/'),
        ),
        migrations.AddField(
            model_name='city',
            name='loop_graphic_webp',
            field=models.ImageField(blank=True, null=True, upload_to='city_loop_graphics/webp/'),
        ),
        migrations.AddField(
            model_name='city',
            name='thumbnail_avif',
            field=models.ImageField(blank=True, null=True, upload_to='city_thumbnails/avif/'),
        ),
        migrations.AddField(
            model_name='city',
            name='thumbnail_original',
            field=models.ImageField(blank=True, null=True, upload_to='city_thumbnails/'),
        ),
        migrations.AddField(
            model_name='city',
            name='thumbnail_webp',
            field=models.ImageField(blank=True, null=True, upload_to='city_thumbnails/webp/'),
        ),
        migrations.AddField(
            model_name='room',
            name='flyin_graphic_avif',
            field=models.ImageField(blank=True, null=True, upload_to='room_flyin_graphics/avif/'),
        ),
        migrations.AddField(
            model_name='room',
            name='flyin_graphic_original',
            field=models.ImageField(blank=True, null=True, upload_to='room_flyin_graphics/'),
        ),
        migrations.AddField(
            model_name='room',
            name='flyin_graphic_webp',
            field=models.ImageField(blank=True, null=True, upload_to='room_flyin_graphics/webp/'),
        ),
        migrations.AddField(
            model_name='room',
            name='loop_graphic_avif',
            field=models.ImageField(blank=True, null=True, upload_to='room_loop_graphics/avif/'),
        ),
        migrations.AddField(
            model_name='room',
            name='loop_graphic_original',
            field=models.ImageField(blank=True, null=True, upload_to='room_loop_graphics/'),
        ),
        migrations.AddField(
            model_name='room',
            name='loop_graphic_webp',
            field=models.ImageField(blank=True, null=True, upload_to='room_loop_graphics/webp/'),
        ),
        migrations.AddField(
            model_name='room',
            name='thumbnail_avif',
            field=models.ImageField(blank=True, null=True, upload_to='room_thumbnails/avif/'),
        ),
        migrations.AddField(
            model_name='room',
            name='thumbnail_original',
            field=models.ImageField(blank=True, null=True, upload_to='room_thumbnails/'),
        ),
        migrations.AddField(
            model_name='room',
            name='thumbnail_webp',
            field=models.ImageField(blank=True, null=True, upload_to='room_thumbnails/webp/'),
        ),
        migrations.AddField(
            model_name='thumbnailasset',
            name='image_avif',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_assets/avif/'),
        ),
        migrations.AddField(
            model_name='thumbnailasset',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_assets/'),
        ),
        migrations.AddField(
            model_name='thumbnailasset',
            name='image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_assets/webp/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_avif',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/avif/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_original',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_webp',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/webp/'),
        ),
        migrations.AlterField(
            model_name='city',
            name='support_audio',
            field=models.FileField(blank=True, null=True, upload_to='city_support_audios/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='support_audio',
            field=models.FileField(blank=True, null=True, upload_to='room_support_audios/'),
        ),
    ]
