# Generated by Django 6.0.4 on 2026-04-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_city_flyin_graphic_remove_city_loop_graphic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
