from django.urls import path
from .views import (
    register,
    login,
    forgot_password,
    reset_password,
    create_city,
    get_cities,
    delete_city,
    create_room,
    get_rooms,
    delete_room,
    get_city,
    update_city,
    request_review_city,
    publish_city,
    get_users,
    get_all_users,   
    create_user,     
    update_user,     
    delete_user,
    get_profile,
    update_profile,
    get_city_by_slug,
    change_password,
    upload_avatar,
    get_room,
    update_room,
    request_review_room,
    publish_room,
    create_event,
    get_events,
    update_event,
    delete_event,
    publish_event,
    get_user_activity_logs,
    get_my_cities,
    get_my_rooms,
    get_my_events,
    get_allowed_rooms,
    get_user_events,
    get_all_thumbnails,
    get_featured_thumbnails,
    create_thumbnail,
    delete_thumbnail,
    toggle_featured_thumbnail,
    update_thumbnail,
    increment_usage_count,
)

urlpatterns = [
    path('register/',register), 
    path('login/',login),
    path('forgot-password/',forgot_password),
    path('reset-password/',reset_password),
    path('cities/create/', create_city),
    path('cities/', get_cities),
    path('cities/slug/<slug:slug>/', get_city_by_slug),
    path('cities/my-cities/', get_my_cities),
    path('cities/<int:city_id>/delete/', delete_city),
    path('rooms/create/', create_room),
    path('rooms/', get_rooms),
    path('rooms/my-rooms/', get_my_rooms),
    path('rooms/allowed/', get_allowed_rooms),
    path('rooms/<int:room_id>/delete/', delete_room),
    path('cities/<int:city_id>/', get_city),
    path('cities/<int:city_id>/update/', update_city),
    path('cities/<int:city_id>/request-review/', request_review_city),
    path('cities/<int:city_id>/publish/', publish_city),
    path('users/', get_users),
    path('users/all/', get_all_users),
    path('users/create/', create_user),
    path('users/<int:user_id>/update/', update_user),
    path('users/<int:user_id>/delete/', delete_user),
    path('users/<int:user_id>/activity/', get_user_activity_logs),
    path('user/profile/', get_profile),
    path('user/profile/update/', update_profile),
    path('user/password/', change_password),
    path('user/avatar/', upload_avatar),
    path('rooms/<int:room_id>/', get_room),
    path('rooms/<int:room_id>/update/', update_room),
    path('rooms/<int:room_id>/request-review/', request_review_room),
    path('rooms/<int:room_id>/publish/', publish_room),
    path('events/create/', create_event),
    path('events/', get_events),
    path('events/my-events/', get_my_events),
    path('events/user-events/', get_user_events),
    path('events/<int:event_id>/update/', update_event),
    path('events/<int:event_id>/delete/', delete_event),
    path('events/<int:event_id>/publish/', publish_event),
    
    # Thumbnail Asset Endpoints
    path('thumbnails/featured/', get_featured_thumbnails),
    path('thumbnails/create/', create_thumbnail),
    path('thumbnails/<int:thumbnail_id>/delete/', delete_thumbnail),
    path('thumbnails/<int:thumbnail_id>/feature/', toggle_featured_thumbnail),
    path('thumbnails/<int:thumbnail_id>/update/', update_thumbnail),
    path('thumbnails/<int:thumbnail_id>/increment-usage/', increment_usage_count),
    path('thumbnails/', get_all_thumbnails),
]
