# Generated by Django 6.0.4 on 2026-04-23 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('assistant', models.CharField(choices=[('assistant1', 'Assistant 1'), ('assistant2', 'Assistant 2'), ('assistant3', 'Assistant 3')], max_length=50)),
                ('meeting_url', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('thumbnail_original', models.ImageField(blank=True, null=True, upload_to='room_thumbnails/')),
                ('thumbnail_webp', models.ImageField(blank=True, null=True, upload_to='room_thumbnails/webp/')),
                ('thumbnail_avif', models.ImageField(blank=True, null=True, upload_to='room_thumbnails/avif/')),
                ('flyin_graphic_original', models.ImageField(blank=True, null=True, upload_to='room_flyin_graphics/')),
                ('flyin_graphic_webp', models.ImageField(blank=True, null=True, upload_to='room_flyin_graphics/webp/')),
                ('flyin_graphic_avif', models.ImageField(blank=True, null=True, upload_to='room_flyin_graphics/avif/')),
                ('loop_graphic_original', models.ImageField(blank=True, null=True, upload_to='room_loop_graphics/')),
                ('loop_graphic_webp', models.ImageField(blank=True, null=True, upload_to='room_loop_graphics/webp/')),
                ('loop_graphic_avif', models.ImageField(blank=True, null=True, upload_to='room_loop_graphics/avif/')),
                ('support_audio', models.FileField(blank=True, null=True, upload_to='room_support_audios/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_rooms', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='cities.city')),
            ],
        ),
    ]
