# Generated by Django 6.0.4 on 2026-04-23 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assistant', models.CharField(choices=[('assistant1', 'Assistant 1'), ('assistant2', 'Assistant 2'), ('assistant3', 'Assistant 3')], max_length=50)),
                ('meeting_url', models.URLField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('thumbnail_original', models.ImageField(blank=True, null=True, upload_to='city_thumbnails/')),
                ('thumbnail_webp', models.ImageField(blank=True, null=True, upload_to='city_thumbnails/webp/')),
                ('thumbnail_avif', models.ImageField(blank=True, null=True, upload_to='city_thumbnails/avif/')),
                ('flyin_graphic_original', models.ImageField(blank=True, null=True, upload_to='city_flyin_graphics/')),
                ('flyin_graphic_webp', models.ImageField(blank=True, null=True, upload_to='city_flyin_graphics/webp/')),
                ('flyin_graphic_avif', models.ImageField(blank=True, null=True, upload_to='city_flyin_graphics/avif/')),
                ('loop_graphic_original', models.ImageField(blank=True, null=True, upload_to='city_loop_graphics/')),
                ('loop_graphic_webp', models.ImageField(blank=True, null=True, upload_to='city_loop_graphics/webp/')),
                ('loop_graphic_avif', models.ImageField(blank=True, null=True, upload_to='city_loop_graphics/avif/')),
                ('support_audio', models.FileField(blank=True, null=True, upload_to='city_support_audios/')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cities', to=settings.AUTH_USER_MODEL)),
                ('content_creator_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
