# Generated by Django 6.0.4 on 2026-04-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='logo_avif',
            field=models.ImageField(blank=True, null=True, upload_to='city_logos/avif/'),
        ),
        migrations.AddField(
            model_name='city',
            name='logo_original',
            field=models.ImageField(blank=True, null=True, upload_to='city_logos/'),
        ),
        migrations.AddField(
            model_name='city',
            name='logo_webp',
            field=models.ImageField(blank=True, null=True, upload_to='city_logos/webp/'),
        ),
        migrations.AddField(
            model_name='city',
            name='navbar_slots',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
